Pandas is a very versatile and open source in python library.
--it is used maily for manuplation and analysis
--pandas introduces two primary structures:Series,Dataframes
--Series - is a one dimensional array which can store any type of data
--Dataframes are 2 Dimensional array and has mutability , hetrogeneous --tabular data structures

#How do you create a Pandas Series from a Python list?

In [9]:
import pandas as pd

In [10]:
data=[10,20,30,40,50,[60,80],(80,9),"Data"]
series=pd.Series(data)
print("Pandas Series:")
print(series)

Pandas Series:
0          10
1          20
2          30
3          40
4          50
5    [60, 80]
6     (80, 9)
7        Data
dtype: object

In [11]:
data=[[10,20,30,40,50,[60,80],(80,90)]]
series=pd.Series(data)
print("Pandas Series:")
print(series)

Pandas Series:
0    [10, 20, 30, 40, 50, [60, 80], (80, 90)]
dtype: object

In [12]:
data={
    "Name":["Alice","Bob","Cherry"],
    "Age":[25,30,35],
    "City":["New York","Austrilia","Los Angels"]

}
df8=pd.DataFrame(data)
print(df8)
df8=pd.DataFrame.from_dict(data)
print(df8)

     Name  Age        City
0   Alice   25    New York
1     Bob   30   Austrilia
2  Cherry   35  Los Angels
     Name  Age        City
0   Alice   25    New York
1     Bob   30   Austrilia
2  Cherry   35  Los Angels

In [13]:
df3 = pd.DataFrame.from_dict({
    "row1": {"Name": "Alice", "Age": 25, "City": "New York"},
    "row2": {"Name": "Bob", "Age": 30, "City": "Los Angeles"},
    "row3": {"Name": "Charlie", "Age": 35, "City": "Los"},
    "row4": {"Name": "Charlie", "Age": 35, "City": "Los"},
    "row5": {"Name": "Charlie", "Age": 35, "City": "Los"},
    "row6": {"Name": "Charlie", "Age": 35, "City": "Los"},
    "row7": {"Name": "Charlie", "Age": 35, "City": "Los"}
}, orient='index')
print("DataFrame with dictionary keys as rows:")
print(df3)

DataFrame with dictionary keys as rows:
         Name  Age         City
row1    Alice   25     New York
row2      Bob   30  Los Angeles
row3  Charlie   35          Los
row4  Charlie   35          Los
row5  Charlie   35          Los
row6  Charlie   35          Los
row7  Charlie   35          Los

In [14]:
#How do you display the first 5 rows of a DataFrame?
data1=df3.iloc[0:6]
print(data1)

         Name  Age         City
row1    Alice   25     New York
row2      Bob   30  Los Angeles
row3  Charlie   35          Los
row4  Charlie   35          Los
row5  Charlie   35          Los
row6  Charlie   35          Los

In [15]:
#How do you display the last 5 rows?
data2=df3.iloc[-5:]
print(data2)

         Name  Age City
row3  Charlie   35  Los
row4  Charlie   35  Los
row5  Charlie   35  Los
row6  Charlie   35  Los
row7  Charlie   35  Los

In [16]:
df3.shape

(7, 3)

In [17]:
df3.size

21

In [18]:
df3.index

Index(['row1', 'row2', 'row3', 'row4', 'row5', 'row6', 'row7'], dtype='str')

In [19]:
df3 = pd.DataFrame.from_dict({
    "row1": {"Name": "Alice", "Age": 25, "City": "New York"},
    "row2": {"Name": "Bob", "Age": 30, "City": "Los Angeles"},
    "row3": {"Name": "Charlie", "Age": 35, "City": "Los"},
    "row4": {"Name": "Charlie", "Age": 35, "City": "Los"},
    "row5": {"Name": "Charlie", "Age": 35, "City": "Los"},
    "row6": {"Name": "Charlie", "Age": 35, "City": "Los"},
    "row7": {"Name": "Charlie", "Age": 35, "City": "Los"}
}, orient='index')

In [20]:
import pandas as pd
sales_data=pd.DataFrame.from_dict({
    "Bangluru":{"Electronics":850000,"Groceries":420000,"Clothing":310000,"Furniture":275000,"Beauty":190000,"Sports":225000},
    "Hyderbad":{"Electronics":780000,"Groceries":460000,"Clothing":295000,"Furniture":310000,"Beauty":210000,"Sports":240000},
    "Chennai":{"Electronics":920000,"Groceries":390000,"Clothing":340000,"Furniture":260000,"Beauty":185000,"Sports":215000},
    "Mumbai":{"Electronics":1050000,"Groceries":510000,"Clothing":375000,"Furniture":345000,"Beauty":250000,"Sports":290000},
    "Pune":{"Electronics":690000,"Groceries":405000,"Clothing":280000,"Furniture":225000,"Beauty":175000,"Sports":205000}
},orient='index')

In [21]:
df=sales_data
print(df)

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000  175000  205000

In [22]:
print(df.shape)

(5, 6)

In [23]:
data=df.values
print(data)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

In [24]:
data=df.keys
print(data)

<bound method NDFrame.keys of           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000  175000  205000>

In [25]:
df.index

Index(['Bangluru', 'Hyderbad', 'Chennai', 'Mumbai', 'Pune'], dtype='str')

In [26]:
df.dtypes

Electronics    int64
Groceries      int64
Clothing       int64
Furniture      int64
Beauty         int64
Sports         int64
dtype: object

In [27]:
df.describe()

,Electronics,Groceries,Clothing,Furniture,Beauty,Sports
count,5.000000e+00,5.000000,5.00000,5.000000,5.000000,5.00000
mean,8.580000e+05,437000.000000,320000.00000,283000.000000,202000.000000,235000.00000
std,1.370036e+05,48425.200051,37914.37722,46178.999556,29706.901555,33354.16016
min,6.900000e+05,390000.000000,280000.00000,225000.000000,175000.000000,205000.00000
25%,7.800000e+05,405000.000000,295000.00000,260000.000000,185000.000000,215000.00000
50%,8.500000e+05,420000.000000,310000.00000,275000.000000,190000.000000,225000.00000
75%,9.200000e+05,460000.000000,340000.00000,310000.000000,210000.000000,240000.00000
max,1.050000e+06,510000.000000,375000.00000,345000.000000,250000.000000,290000.00000

In [28]:
df.isnull()

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru        False      False     False      False   False   False
Hyderbad        False      False     False      False   False   False
Chennai         False      False     False      False   False   False
Mumbai          False      False     False      False   False   False
Pune            False      False     False      False   False   False

In [29]:
df.iloc[3]

Electronics    1050000
Groceries       510000
Clothing        375000
Furniture       345000
Beauty          250000
Sports          290000
Name: Mumbai, dtype: int64

In [30]:
df.loc["Mumbai"]

Electronics    1050000
Groceries       510000
Clothing        375000
Furniture       345000
Beauty          250000
Sports          290000
Name: Mumbai, dtype: int64

In [31]:
print(df.iloc[0])
print(df.iloc[2])

Electronics    850000
Groceries      420000
Clothing       310000
Furniture      275000
Beauty         190000
Sports         225000
Name: Bangluru, dtype: int64
Electronics    920000
Groceries      390000
Clothing       340000
Furniture      260000
Beauty         185000
Sports         215000
Name: Chennai, dtype: int64

In [32]:
df.iloc[:,0]

Bangluru     850000
Hyderbad     780000
Chennai      920000
Mumbai      1050000
Pune         690000
Name: Electronics, dtype: int64

In [33]:
df.loc["Mumbai"]

Electronics    1050000
Groceries       510000
Clothing        375000
Furniture       345000
Beauty          250000
Sports          290000
Name: Mumbai, dtype: int64

In [34]:
df.iloc[0:3]

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000

In [35]:
df.iloc[:,-2:]

          Beauty  Sports
Bangluru  190000  225000
Hyderbad  210000  240000
Chennai   185000  215000
Mumbai    250000  290000
Pune      175000  205000

In [36]:
#. Display the first 3 rows.
df.head(3)

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000

In [37]:
#Display the last 2 rows.
df.tail(3)

         Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Chennai       920000     390000    340000     260000  185000  215000
Mumbai       1050000     510000    375000     345000  250000  290000
Pune          690000     405000    280000     225000  175000  205000

In [38]:
#Find the number of rows and columns.
df.shape

(5, 6)

In [39]:
df.columns

Index(['Electronics', 'Groceries', 'Clothing', 'Furniture', 'Beauty',
       'Sports'],
      dtype='str')

In [40]:
print(df.rpow)

<bound method DataFrame.rpow of           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000  175000  205000>

In [41]:
#Find the index names.
df.index

Index(['Bangluru', 'Hyderbad', 'Chennai', 'Mumbai', 'Pune'], dtype='str')

In [42]:
#Find the total number of elements in the DataFrame.
df.size

30

In [43]:
#Find the data type of every column.
df.dtypes

Electronics    int64
Groceries      int64
Clothing       int64
Furniture      int64
Beauty         int64
Sports         int64
dtype: object

In [44]:
#Get complete information about the DataFrame.
df.info()

<class 'pandas.DataFrame'>
Index: 5 entries, Bangluru to Pune
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Electronics  5 non-null      int64
 1   Groceries    5 non-null      int64
 2   Clothing     5 non-null      int64
 3   Furniture    5 non-null      int64
 4   Beauty       5 non-null      int64
 5   Sports       5 non-null      int64
dtypes: int64(6)
memory usage: 485.0 bytes

In [45]:
#Display only the Electronics column.
df.iloc[:,0]

Bangluru     850000
Hyderbad     780000
Chennai      920000
Mumbai      1050000
Pune         690000
Name: Electronics, dtype: int64

In [46]:
#Display Electronics and Groceries.
df.iloc[:,0:2]

          Electronics  Groceries
Bangluru       850000     420000
Hyderbad       780000     460000
Chennai        920000     390000
Mumbai        1050000     510000
Pune           690000     405000

In [47]:
#Display Clothing, Furniture, and Sports.
print(df.iloc[:,2:4],df.iloc[:,-1])

          Clothing  Furniture
Bangluru    310000     275000
Hyderbad    295000     310000
Chennai     340000     260000
Mumbai      375000     345000
Pune        280000     225000 Bangluru    225000
Hyderbad    240000
Chennai     215000
Mumbai      290000
Pune        205000
Name: Sports, dtype: int64

In [48]:
#Display all columns except Beauty.
df.iloc[:,-2].drop

<bound method Series.drop of Bangluru    190000
Hyderbad    210000
Chennai     185000
Mumbai      250000
Pune        175000
Name: Beauty, dtype: int64>

In [49]:
df.iloc[:,0:4],df.iloc[:,-1]

(          Electronics  Groceries  Clothing  Furniture
 Bangluru       850000     420000    310000     275000
 Hyderbad       780000     460000    295000     310000
 Chennai        920000     390000    340000     260000
 Mumbai        1050000     510000    375000     345000
 Pune           690000     405000    280000     225000,
 Bangluru    225000
 Hyderbad    240000
 Chennai     215000
 Mumbai      290000
 Pune        205000
 Name: Sports, dtype: int64)

In [50]:
#Create a new column called Total_Sales containing the total sales of each city.
df.sum(axis=1)

Bangluru    2270000
Hyderbad    2295000
Chennai     2310000
Mumbai      2820000
Pune        1980000
dtype: int64

**Level 3 — Indexing with loc and iloc**

In [51]:
#Display the sales data of Mumbai.
df.loc["Mumbai"]

Electronics    1050000
Groceries       510000
Clothing        375000
Furniture       345000
Beauty          250000
Sports          290000
Name: Mumbai, dtype: int64

In [52]:
#Display the sales data of Chennai and Pune.
df.loc["Chennai"],df.loc["Pune"]

(Electronics    920000
 Groceries      390000
 Clothing       340000
 Furniture      260000
 Beauty         185000
 Sports         215000
 Name: Chennai, dtype: int64,
 Electronics    690000
 Groceries      405000
 Clothing       280000
 Furniture      225000
 Beauty         175000
 Sports         205000
 Name: Pune, dtype: int64)

In [53]:
#Display only the Electronics sales of Mumbai.
df.iloc[3,0]

np.int64(1050000)

In [54]:
#Display Electronics and Clothing sales of Mumbai.
print(df.iloc[3,0],df.iloc[3,2])

1050000 375000

In [55]:
#Using iloc, display the first row.
df.iloc[0,:]

Electronics    850000
Groceries      420000
Clothing       310000
Furniture      275000
Beauty         190000
Sports         225000
Name: Bangluru, dtype: int64

In [56]:
#. Using iloc, display the last row.
df.tail(1)

      Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Pune       690000     405000    280000     225000  175000  205000

In [57]:
#Using iloc, display the first 3 rows.
print(df.head(3))
print(df.iloc[0:3])

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000

In [58]:
#Using iloc, display the first 3 columns.
df.iloc[:,0:3]

          Electronics  Groceries  Clothing
Bangluru       850000     420000    310000
Hyderbad       780000     460000    295000
Chennai        920000     390000    340000
Mumbai        1050000     510000    375000
Pune           690000     405000    280000

In [59]:
#Using loc, display rows from Chennai to Pune.
df.loc["Chennai"],df.loc["Pune"]

(Electronics    920000
 Groceries      390000
 Clothing       340000
 Furniture      260000
 Beauty         185000
 Sports         215000
 Name: Chennai, dtype: int64,
 Electronics    690000
 Groceries      405000
 Clothing       280000
 Furniture      225000
 Beauty         175000
 Sports         205000
 Name: Pune, dtype: int64)

In [60]:
#Using loc, display Electronics, Furniture, and Sports for Mumbai and Pune.
df.loc[["Mumbai","Pune"],["Electronics","Furniture","Sports"]]

        Electronics  Furniture  Sports
Mumbai      1050000     345000  290000
Pune         690000     225000  205000

**Level 4 — Filtering**

In [61]:
#Find cities where Electronics sales are greater than 800000.
greater=df[df["Electronics"]>800000]
greater

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000

In [62]:
import numpy as np
greater=np.where(df["Electronics"]>800000)
print(greater)

(array([0, 2, 3]),)

In [63]:
df.iloc[np.where(df["Electronics"]>800000)[0]]
# print(great)

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000

In [64]:
#. Find cities where Groceries sales are greater than 400000.
print(np.where(df["Groceries"]>400000))
print(df.iloc[np.where(df["Groceries"]>400000)[0]])

(array([0, 1, 3, 4]),)
          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000  175000  205000

In [65]:
#. Find cities where Clothing sales are less than 300000.
print(df.iloc[np.where(df["Clothing"]>300000)[0]])

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000

In [66]:
#Find cities where Electronics sales are between 700000 and 900000.
cities=df.iloc[np.where((df["Electronics"]<=700000) & (df["Electronics"]>=900000))[0]]
print(cities)

Empty DataFrame
Columns: [Electronics, Groceries, Clothing, Furniture, Beauty, Sports]
Index: []

In [67]:
result=df.loc[
    (df["Electronics"]<=700000)|
    (df["Electronics"]>=900000)

]
print(result)

         Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Chennai       920000     390000    340000     260000  185000  215000
Mumbai       1050000     510000    375000     345000  250000  290000
Pune          690000     405000    280000     225000  175000  205000

In [68]:
print(df["Electronics"].describe())

count    5.000000e+00
mean     8.580000e+05
std      1.370036e+05
min      6.900000e+05
25%      7.800000e+05
50%      8.500000e+05
75%      9.200000e+05
max      1.050000e+06
Name: Electronics, dtype: float64

In [69]:
#Find cities where Electronics sales are greater than 800000 AND Groceries sales are greater than 400000.
result=df.iloc[np.where((df["Electronics"]>800000) & (df["Groceries"]>400000))[0]]
print(result)

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Mumbai        1050000     510000    375000     345000  250000  290000

In [70]:
df.loc[
    (df["Electronics"]>800000)&
    (df["Groceries"]>400000)
]

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Mumbai        1050000     510000    375000     345000  250000  290000

In [71]:
#Find cities where Electronics sales are greater than 900000 OR Furniture sales are greater than 300000.
df.loc[
    (df["Electronics"]>900000)|
    (df["Furniture"]>300000)
]

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000

In [72]:
print(df.index[
    (df["Electronics"]>900000)|
    (df["Furniture"]>300000)
])

Index(['Hyderbad', 'Chennai', 'Mumbai'], dtype='str')

In [73]:
result = df.loc[
    (df["Electronics"] > 900000) |
    (df["Furniture"] > 300000),
    ["Electronics", "Furniture"]
]

print(result)

          Electronics  Furniture
Hyderbad       780000     310000
Chennai        920000     260000
Mumbai        1050000     345000

In [74]:
# Find cities where Beauty sales are not greater than 200000.
df.loc[df["Beauty"]<200000]

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Chennai        920000     390000    340000     260000  185000  215000
Pune           690000     405000    280000     225000  175000  205000

In [75]:
#Find cities whose name is either Mumbai or Pune.

# Hint: isin()

df[df.index.isin(["Mumbai","Pune"])]

        Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Mumbai      1050000     510000    375000     345000  250000  290000
Pune         690000     405000    280000     225000  175000  205000

In [76]:
#Level 5 — Adding and Modifying Columns
total_sales=df.sum(axis=0)
print(total_sales)

Electronics    4290000
Groceries      2185000
Clothing       1600000
Furniture      1415000
Beauty         1010000
Sports         1175000
dtype: int64

In [77]:
#Create a Total_Sales column.
df.sum().sum()

np.int64(11675000)

In [78]:
#Create an Average_Sales column.
df.mean(axis=0)

Electronics    858000.0
Groceries      437000.0
Clothing       320000.0
Furniture      283000.0
Beauty         202000.0
Sports         235000.0
dtype: float64

In [79]:
#Create a Highest_Category column containing the category with the highest sales for each city.
df.max(axis=1)

Bangluru     850000
Hyderbad     780000
Chennai      920000
Mumbai      1050000
Pune         690000
dtype: int64

In [80]:
#Create a Lowest_Category column containing the category with the lowest sales for each city.
df.min(axis=1)

Bangluru    190000
Hyderbad    210000
Chennai     185000
Mumbai      250000
Pune        175000
dtype: int64

In [81]:
#Increase all sales by 10%.
discount=df.multiply(0.10)
total=discount+sales_data
print(total)

          Electronics  Groceries  Clothing  Furniture    Beauty    Sports
Bangluru     935000.0   462000.0  341000.0   302500.0  209000.0  247500.0
Hyderbad     858000.0   506000.0  324500.0   341000.0  231000.0  264000.0
Chennai     1012000.0   429000.0  374000.0   286000.0  203500.0  236500.0
Mumbai      1155000.0   561000.0  412500.0   379500.0  275000.0  319000.0
Pune         759000.0   445500.0  308000.0   247500.0  192500.0  225500.0

In [82]:
#Increase all Electronics sales by 10%.
Electronic=df["Electronics"]*0.10
total_electronic=df["Electronics"]+Electronic
print(total_electronic)

Bangluru     935000.0
Hyderbad     858000.0
Chennai     1012000.0
Mumbai      1155000.0
Pune         759000.0
Name: Electronics, dtype: float64

In [83]:
#Reduce all Beauty sales by 5%.
reduce=df["Beauty"]*0.05
reduce_beu=df["Beauty"]-reduce
print(reduce_beu)

Bangluru    180500.0
Hyderbad    199500.0
Chennai     175750.0
Mumbai      237500.0
Pune        166250.0
Name: Beauty, dtype: float64

In [84]:
#Create a column Electronics_Percentage showing Electronics sales as a percentage of Total Sales.
electry_percentage=df["Electronics"]/df.sum(axis=1)*100
print(electry_percentage)

Bangluru    37.444934
Hyderbad    33.986928
Chennai     39.826840
Mumbai      37.234043
Pune        34.848485
dtype: float64

**Level 6 — sum(), mean(), min(), max()**

In [85]:
#Find the total sales of each city.
sales=df.sum(axis=1)
print(sales)

Bangluru    2270000
Hyderbad    2295000
Chennai     2310000
Mumbai      2820000
Pune        1980000
dtype: int64

In [86]:
#Find the average sales of each city.
average=df.mean(axis=1)
print(average)

Bangluru    378333.333333
Hyderbad    382500.000000
Chennai     385000.000000
Mumbai      470000.000000
Pune        330000.000000
dtype: float64

In [87]:
#Find the maximum sales in each city.
df.max(axis=1)

Bangluru     850000
Hyderbad     780000
Chennai      920000
Mumbai      1050000
Pune         690000
dtype: int64

In [88]:
#Find the minimum sales in each city.
df.min(axis=1)

Bangluru    190000
Hyderbad    210000
Chennai     185000
Mumbai      250000
Pune        175000
dtype: int64

In [89]:
#Find the total sales of each category across all cities.
df.sum(axis=0)

Electronics    4290000
Groceries      2185000
Clothing       1600000
Furniture      1415000
Beauty         1010000
Sports         1175000
dtype: int64

In [90]:
#Find the average Electronics sales.
df["Electronics"].mean()

np.float64(858000.0)

In [91]:
#Find the highest Electronics sales.
df["Electronics"].max()

np.int64(1050000)

In [92]:
#Find the lowest Furniture sales.
df["Furniture"].min()

np.int64(225000)

In [93]:
#Which city has the highest total sales?
total=df.sum(axis=1)
index=total.idxmax()
max_total=total.max()
# print(total)
print(index)
# print(total.loc[index])
print(max_total)

Mumbai
2820000

In [94]:
#Which city has the lowest total sales?
city=df.sum(axis=1)
# print(city)
min_sales=city.min()
print(min_sales)
index=city.idxmin()
print(index)

1980000
Pune

**Level 7 — idxmax() and idxmin()**

In [95]:
#Find the city with the highest Electronics sales.
city=df["Electronics"].idxmax()
max_city=df["Electronics"].max()
print(city,max_city)

Mumbai 1050000

In [96]:
#. Find the city with the lowest Electronics sales.
city=df["Electronics"].idxmin()
min_city=df["Electronics"].min()
print(city,min_city)

Pune 690000

In [97]:
#Find the city with the highest Groceries sales.
city=df["Groceries"].idxmax()
gro_city=df["Groceries"].max()
print(city,gro_city)

Mumbai 510000

In [98]:
#. Find the category with the highest sales in Mumbai.
df

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000  175000  205000

In [99]:
#Find the category with the highest sales in Mumbai.
city=df.loc["Mumbai"].idxmax()
max_city=df.loc["Mumbai"].max()
print(city,max_city)

Electronics 1050000

In [100]:
#. Find the category with the lowest sales in Pune.
low=df.loc["Pune"].idxmin()
low_cat=df.loc["Pune"].max()
print(low,low_cat)

Beauty 690000

In [101]:
#Find the highest-selling category overall.
category_sale=df.sum()
print(category_sale)
high_cat=category_sale.idxmax()
hig_sell=category_sale.max()
print(high_cat,hig_sell)

Electronics    4290000
Groceries      2185000
Clothing       1600000
Furniture      1415000
Beauty         1010000
Sports         1175000
dtype: int64
Electronics 4290000

In [102]:

over=df.iloc[:,:].idxmax(axis=1)
ma=df.iloc[:,:].max()
print(over,ma)

Bangluru    Electronics
Hyderbad    Electronics
Chennai     Electronics
Mumbai      Electronics
Pune        Electronics
dtype: str Electronics    1050000
Groceries       510000
Clothing        375000
Furniture       345000
Beauty          250000
Sports          290000
dtype: int64

In [103]:
city=df.max(axis=1).max()
ma_ci=df.max()
print(ma_ci)

Electronics    1050000
Groceries       510000
Clothing        375000
Furniture       345000
Beauty          250000
Sports          290000
dtype: int64

**Level 8 — Sorting**

In [104]:
#Sort cities according to Electronics sales in ascending order.
df.sort_values("Electronics")

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Pune           690000     405000    280000     225000  175000  205000
Hyderbad       780000     460000    295000     310000  210000  240000
Bangluru       850000     420000    310000     275000  190000  225000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000

In [105]:
#Sort cities according to Electronics sales in descending order.
df.sort_values("Electronics",ascending=False)

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Mumbai        1050000     510000    375000     345000  250000  290000
Chennai        920000     390000    340000     260000  185000  215000
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Pune           690000     405000    280000     225000  175000  205000

In [106]:
#Sort according to Total Sales from highest to lowest.
sale=df.sum(axis=1)
valu=sale.sort_values(ascending=False)
print(sale)
print(valu)

Bangluru    2270000
Hyderbad    2295000
Chennai     2310000
Mumbai      2820000
Pune        1980000
dtype: int64
Mumbai      2820000
Chennai     2310000
Hyderbad    2295000
Bangluru    2270000
Pune        1980000
dtype: int64

In [107]:
#Sort according to Electronics first and Groceries second.
print(df.sort_values("Electronics"))
print(df.sort_values("Groceries"))

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Pune           690000     405000    280000     225000  175000  205000
Hyderbad       780000     460000    295000     310000  210000  240000
Bangluru       850000     420000    310000     275000  190000  225000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000
          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Chennai        920000     390000    340000     260000  185000  215000
Pune           690000     405000    280000     225000  175000  205000
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Mumbai        1050000     510000    375000     345000  250000  290000

In [108]:
print(df.sort_values(["Electronics","Groceries"], ascending=[True, True]))

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Pune           690000     405000    280000     225000  175000  205000
Hyderbad       780000     460000    295000     310000  210000  240000
Bangluru       850000     420000    310000     275000  190000  225000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000

In [109]:
# Sort the index in descending order.
ind=df.sort_index(ascending=False)
print(ind)

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Pune           690000     405000    280000     225000  175000  205000
Mumbai        1050000     510000    375000     345000  250000  290000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Bangluru       850000     420000    310000     275000  190000  225000

**Level 9 — axis**

In [110]:
#Calculate the total sales across all categories for each city.
total=df.sum(axis=1)
print(total)

Bangluru    2270000
Hyderbad    2295000
Chennai     2310000
Mumbai      2820000
Pune        1980000
dtype: int64

In [111]:
#Calculate total sales of each category across all cities.
print(df.sum(axis=0))

Electronics    4290000
Groceries      2185000
Clothing       1600000
Furniture      1415000
Beauty         1010000
Sports         1175000
dtype: int64

In [112]:
#Calculate the average sales across categories for every city.
print(round(df.mean(axis=1),2))

Bangluru    378333.33
Hyderbad    382500.00
Chennai     385000.00
Mumbai      470000.00
Pune        330000.00
dtype: float64

In [113]:
#Find the maximum value across each row.
df.max(axis=1)

Bangluru     850000
Hyderbad     780000
Chennai      920000
Mumbai      1050000
Pune         690000
dtype: int64

In [114]:
#Find the maximum value across each column.
df.max(axis=0)

Electronics    1050000
Groceries       510000
Clothing        375000
Furniture       345000
Beauty          250000
Sports          290000
dtype: int64

**Level 10 — apply()**

In [115]:
#Use apply() to calculate Total Sales for every city.
to=df.apply(lambda x:x.sum(),axis=1)
print(to)

Bangluru    2270000
Hyderbad    2295000
Chennai     2310000
Mumbai      2820000
Pune        1980000
dtype: int64

In [116]:
#Use apply() to classify cities:
# "High" if Total Sales > 2,500,000
# "Medium" if Total Sales between 2,000,000 and 2,500,000
# "Low" otherwise.
df.apply(lambda x : "High" if x.sum()>2500000 else "Medium" if ((x.sum()>=2000000) & (x.sum()<=2500000)) else "Low",axis=1)

Bangluru    Medium
Hyderbad    Medium
Chennai     Medium
Mumbai        High
Pune           Low
dtype: str

In [117]:
#Use apply() to find the highest-selling category for each city.
df.apply(lambda x : x.max(),axis=0)

Electronics    1050000
Groceries       510000
Clothing        375000
Furniture       345000
Beauty          250000
Sports          290000
dtype: int64

In [118]:
df

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000  175000  205000

In [119]:
#Use apply() to calculate the percentage contribution of Electronics to Total Sales.
tota=df.sum().sum()
to=df["Electronics"].sum()
cal=to/tota*100
print(cal)

36.74518201284796

**Level 11 — map()**

In [120]:
sales_data

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000  175000  205000

In [121]:
#Rename the cities using map():
df.index.map({
    "Bangluru":"Bengaluru",
    "Hyderbad":"Hyderabad"
})

Index(['Bengaluru', 'Hyderabad', nan, nan, nan], dtype='str')

In [122]:
#Convert the city names to uppercase using a suitable Pandas string operation.
df.index.map({
    "Bangluru":"BANGLURU",
    "Hyderbad":"HYDERBAD",
    "Chennai":"CHENNAI",
    "Mumbai":"MUMBAI",
    "Pune":"PUNE"
})

Index(['BANGLURU', 'HYDERBAD', 'CHENNAI', 'MUMBAI', 'PUNE'], dtype='str')

In [123]:
df.index.str.upper()

Index(['BANGLURU', 'HYDERBAD', 'CHENNAI', 'MUMBAI', 'PUNE'], dtype='str')

In [124]:
#. Create a dictionary:
#Use it to create a new DataFrame with abbreviated column names.

new_cols=df.copy()
new_cols.columns=df.columns.map({
    "Electronics": "E",
    "Groceries": "G",
    "Clothing": "C",
    "Furniture": "F",
    "Beauty": "B",
    "Sports": "S"
})
print(new_cols)

                E       G       C       F       B       S
Bangluru   850000  420000  310000  275000  190000  225000
Hyderbad   780000  460000  295000  310000  210000  240000
Chennai    920000  390000  340000  260000  185000  215000
Mumbai    1050000  510000  375000  345000  250000  290000
Pune       690000  405000  280000  225000  175000  205000

In [125]:
abbreviations = {
    "Electronics": "E",
    "Groceries": "G",
    "Clothing": "C",
    "Furniture": "F",
    "Beauty": "B",
    "Sports": "S"
}

new_df = df.copy()
new_df.columns = new_df.columns.map(abbreviations)

print(new_df)

                E       G       C       F       B       S
Bangluru   850000  420000  310000  275000  190000  225000
Hyderbad   780000  460000  295000  310000  210000  240000
Chennai    920000  390000  340000  260000  185000  215000
Mumbai    1050000  510000  375000  345000  250000  290000
Pune       690000  405000  280000  225000  175000  205000

In [126]:
#Level 12 — rename()
df.rename({
    "Bengluru":"Bengaluru",
    "Hyderbad":"Hyderabad"
})

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru        850000     420000    310000     275000  190000  225000
Hyderabad       780000     460000    295000     310000  210000  240000
Chennai         920000     390000    340000     260000  185000  215000
Mumbai         1050000     510000    375000     345000  250000  290000
Pune            690000     405000    280000     225000  175000  205000

In [127]:
df.rename(columns={
    "Electronics":"Electronics_Sales",
    "Groceries":"Grocery_Sales"
    })

,Electronics_Sales,Grocery_Sales,Clothing,Furniture,Beauty,Sports
Bangluru,850000,420000,310000,275000,190000,225000
Hyderbad,780000,460000,295000,310000,210000,240000
Chennai,920000,390000,340000,260000,185000,215000
Mumbai,1050000,510000,375000,345000,250000,290000
Pune,690000,405000,280000,225000,175000,205000

In [128]:
#Rename all columns to lowercase.
df.rename(columns=str.lower)

          electronics  groceries  clothing  furniture  beauty  sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000  175000  205000

**#Level 13 — drop()**

In [129]:

#Remove the Beauty column.

df.drop(columns="Beauty")

          Electronics  Groceries  Clothing  Furniture  Sports
Bangluru       850000     420000    310000     275000  225000
Hyderbad       780000     460000    295000     310000  240000
Chennai        920000     390000    340000     260000  215000
Mumbai        1050000     510000    375000     345000  290000
Pune           690000     405000    280000     225000  205000

In [130]:
#Remove Sports and Furniture.
df.drop(columns=["Furniture","Sports"])

          Electronics  Groceries  Clothing  Beauty
Bangluru       850000     420000    310000  190000
Hyderbad       780000     460000    295000  210000
Chennai        920000     390000    340000  185000
Mumbai        1050000     510000    375000  250000
Pune           690000     405000    280000  175000

In [131]:
#Remove the Pune row.
df.drop(index="Pune")

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000

In [132]:
#Remove Chennai and Hyderbad.
df.drop(index=["Chennai","Hyderbad"])

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000  175000  205000

In [133]:
#Remove Total_Sales after creating it.
df["total_sales"]=df.sum(axis=1)
print(df["total_sales"])

Bangluru    2270000
Hyderbad    2295000
Chennai     2310000
Mumbai      2820000
Pune        1980000
Name: total_sales, dtype: int64

In [134]:
df.drop(columns="total_sales")

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000  175000  205000

**Level 14 — query()**

In [135]:
#Using query(), find cities where Electronics sales are greater than 800000.
df.query("Electronics> 800000")

,Electronics,Groceries,Clothing,Furniture,Beauty,Sports,total_sales
Bangluru,850000,420000,310000,275000,190000,225000,2270000
Chennai,920000,390000,340000,260000,185000,215000,2310000
Mumbai,1050000,510000,375000,345000,250000,290000,2820000

In [136]:
#Using query(), find cities where:
# #Electronics > 800000
# AND
# Groceries > 400000
df.query("Electronics>800000" and "Groceries>400000")

,Electronics,Groceries,Clothing,Furniture,Beauty,Sports,total_sales
Bangluru,850000,420000,310000,275000,190000,225000,2270000
Hyderbad,780000,460000,295000,310000,210000,240000,2295000
Mumbai,1050000,510000,375000,345000,250000,290000,2820000
Pune,690000,405000,280000,225000,175000,205000,1980000

In [137]:
df

,Electronics,Groceries,Clothing,Furniture,Beauty,Sports,total_sales
Bangluru,850000,420000,310000,275000,190000,225000,2270000
Hyderbad,780000,460000,295000,310000,210000,240000,2295000
Chennai,920000,390000,340000,260000,185000,215000,2310000
Mumbai,1050000,510000,375000,345000,250000,290000,2820000
Pune,690000,405000,280000,225000,175000,205000,1980000

In [138]:
#Using query(), find cities where:
df.query("Clothing>300000" or "Beauty>200000")

,Electronics,Groceries,Clothing,Furniture,Beauty,Sports,total_sales
Bangluru,850000,420000,310000,275000,190000,225000,2270000
Chennai,920000,390000,340000,260000,185000,215000,2310000
Mumbai,1050000,510000,375000,345000,250000,290000,2820000

In [139]:
df["total_sales"].drop

<bound method Series.drop of Bangluru    2270000
Hyderbad    2295000
Chennai     2310000
Mumbai      2820000
Pune        1980000
Name: total_sales, dtype: int64>

In [140]:
df.drop(columns="total_sales",inplace=True)

In [141]:
df

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000  175000  205000

**Level 15 — nunique(), unique(), value_counts()**

In [142]:
df.apply(lambda x : "High" if x.sum()>2500000 else "Medium" if ((x.sum()>=2000000) & (x.sum()<=2500000)) else "Low",axis=1)

Bangluru    Medium
Hyderbad    Medium
Chennai     Medium
Mumbai        High
Pune           Low
dtype: str

In [143]:
#Create a column called Performance:
df["Total_sales"]=df.sum(axis=1,numeric_only=True)
df["Performance"]=df["Total_sales"].apply(lambda x:"High" if x>2500000 
                           else "Medium" if x>=2000000 
                           else "Low",
                           )


df["Performance"].unique()

<ArrowStringArray>
['Medium', 'High', 'Low']
Length: 3, dtype: str

In [144]:
df["Performance"].nunique()

3

In [145]:
df

,Electronics,Groceries,Clothing,Furniture,Beauty,Sports,Total_sales,Performance
Bangluru,850000,420000,310000,275000,190000,225000,2270000,Medium
Hyderbad,780000,460000,295000,310000,210000,240000,2295000,Medium
Chennai,920000,390000,340000,260000,185000,215000,2310000,Medium
Mumbai,1050000,510000,375000,345000,250000,290000,2820000,High
Pune,690000,405000,280000,225000,175000,205000,1980000,Low

In [146]:
df.drop(columns="Total_sales",inplace=True)

In [147]:
df

,Electronics,Groceries,Clothing,Furniture,Beauty,Sports,Performance
Bangluru,850000,420000,310000,275000,190000,225000,Medium
Hyderbad,780000,460000,295000,310000,210000,240000,Medium
Chennai,920000,390000,340000,260000,185000,215000,Medium
Mumbai,1050000,510000,375000,345000,250000,290000,High
Pune,690000,405000,280000,225000,175000,205000,Low

In [148]:
#Find the number of unique performance categories.
df["Performance"].nunique()

3

In [149]:
#Count how many cities belong to each performance category.
df["Performance"].value_counts()

Performance
Medium    3
High      1
Low       1
Name: count, dtype: int64

In [239]:
# df=df.drop(columns=["Performance","Total_sales"])

In [ ]:
df

          Electronics  Groceries  Clothing  Furniture    Beauty  Sports
Bangluru       850000     420000    310000     275000  190000.0  225000
Hyderbad       780000     460000    295000     310000  210000.0  240000
Chennai        920000     390000    340000     260000  185000.0  215000
Mumbai        1050000     510000    375000     345000  250000.0  290000
Pune           690000     405000    280000     225000       NaN  205000

In [ ]:
df.loc["Pune","Beauty"]=None
df

          Electronics  Groceries  Clothing  Furniture    Beauty  Sports
Bangluru       850000     420000    310000     275000  190000.0  225000
Hyderbad       780000     460000    295000     310000  210000.0  240000
Chennai        920000     390000    340000     260000  185000.0  215000
Mumbai        1050000     510000    375000     345000  250000.0  290000
Pune           690000     405000    280000     225000       NaN  205000

In [ ]:
#Count missing values in every column.
miss=df.isna().sum()
print(miss)

Electronics    0
Groceries      0
Clothing       0
Furniture      0
Beauty         1
Sports         0
dtype: int64

In [ ]:
#Find the total number of missing values.
df.isna().sum().sum()

np.int64(1)

In [ ]:
#Fill the missing Beauty value with the average Beauty sales.
df.fillna(175000,inplace=True).astype(int)

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000  175000  205000

In [ ]:
df.loc["Pune","Beauty"]=None

In [ ]:
df

          Electronics  Groceries  Clothing  Furniture    Beauty  Sports
Bangluru       850000     420000    310000     275000  190000.0  225000
Hyderbad       780000     460000    295000     310000  210000.0  240000
Chennai        920000     390000    340000     260000  185000.0  215000
Mumbai        1050000     510000    375000     345000  250000.0  290000
Pune           690000     405000    280000     225000       NaN  205000

In [ ]:
#Drop rows containing missing values.
df.dropna(axis=1,how="any")

          Electronics  Groceries  Clothing  Furniture  Sports
Bangluru       850000     420000    310000     275000  225000
Hyderbad       780000     460000    295000     310000  240000
Chennai        920000     390000    340000     260000  215000
Mumbai        1050000     510000    375000     345000  290000
Pune           690000     405000    280000     225000  205000

In [ ]:
#Replace missing values with 0.
df.fillna(0).astype(int)

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000       0  205000

In [ ]:
df=df.fillna(175000,inplace=True).astype(int)

**Level 17 — Duplicates**

In [ ]:
df.loc["Pune_copy"]=df.loc["Pune"]
df.loc["Pune_copy"]

Electronics    690000
Groceries      405000
Clothing       280000
Furniture      225000
Beauty         175000
Sports         205000
Name: Pune_copy, dtype: int64

In [ ]:
df

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru        850000     420000    310000     275000  190000  225000
Hyderbad        780000     460000    295000     310000  210000  240000
Chennai         920000     390000    340000     260000  185000  215000
Mumbai         1050000     510000    375000     345000  250000  290000
Pune            690000     405000    280000     225000  175000  205000
Pune_copy       690000     405000    280000     225000  175000  205000

In [ ]:
#Check whether duplicate rows exist.
df.duplicated()

Bangluru     False
Hyderbad     False
Chennai      False
Mumbai       False
Pune         False
Pune_copy     True
dtype: bool

In [ ]:
#Find duplicate rows.
df.duplicated().sum()

np.int64(1)

In [ ]:
# To actually see the duplicate rows
df[df.duplicated()]

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Pune_copy       690000     405000    280000     225000  175000  205000

In [ ]:
# Remove duplicate rows.
df=df.drop_duplicates()
df

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000  175000  205000

**Level 18 — String Functions**

In [ ]:
#Convert all city names to uppercase.
df.index.str.upper()

Index(['BANGLURU', 'HYDERBAD', 'CHENNAI', 'MUMBAI', 'PUNE'], dtype='str')

In [ ]:
#Convert all city names to lowercase.
df.index.str.lower()

Index(['bangluru', 'hyderbad', 'chennai', 'mumbai', 'pune'], dtype='str')

In [ ]:
df

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000  175000  205000

In [ ]:
#Find cities whose names contain the letter "u".
df[df.index.str.contains("u",case=False,na=False)]

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000  175000  205000

In [ ]:
#Find cities whose names start with "M".
df[df.index.str.startswith("M")]

        Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Mumbai      1050000     510000    375000     345000  250000  290000

In [ ]:
#. Find the length of every city name.
df.index.str.len()

Index([8, 8, 7, 6, 4], dtype='int64')

In [ ]:
#Transpose the DataFrame.
new=new_df.T.copy(deep=True)
new

   Bangluru  Hyderbad  Chennai   Mumbai    Pune
E    850000    780000   920000  1050000  690000
G    420000    460000   390000   510000  405000
C    310000    295000   340000   375000  280000
F    275000    310000   260000   345000  225000
B    190000    210000   185000   250000  175000
S    225000    240000   215000   290000  205000

In [ ]:
#After transposing, find Electronics, Groceries, etc. as rows.

new.index

Index(['E', 'G', 'C', 'F', 'B', 'S'], dtype='str')

In [ ]:
#Calculate the total sales for each category after transposing.
new.sum()

Bangluru    2270000
Hyderbad    2295000
Chennai     2310000
Mumbai      2820000
Pune        1980000
dtype: int64

**Level 20 — reset_index() and set_index()**

In [ ]:
#Convert the city index into a normal column.
new.reset_index()

  index  Bangluru  Hyderbad  Chennai   Mumbai    Pune
0     E    850000    780000   920000  1050000  690000
1     G    420000    460000   390000   510000  405000
2     C    310000    295000   340000   375000  280000
3     F    275000    310000   260000   345000  225000
4     B    190000    210000   185000   250000  175000
5     S    225000    240000   215000   290000  205000

In [ ]:
#Set Bangluru, Hyderbad, etc. back as the index.
new.T

                E       G       C       F       B       S
Bangluru   850000  420000  310000  275000  190000  225000
Hyderbad   780000  460000  295000  310000  210000  240000
Chennai    920000  390000  340000  260000  185000  215000
Mumbai    1050000  510000  375000  345000  250000  290000
Pune       690000  405000  280000  225000  175000  205000

**Level 21 — groupby()**

In [ ]:
#Find total sales by category.
df.sum(axis=0)

Electronics    4290000
Groceries      2185000
Clothing       1600000
Furniture      1415000
Beauty         1010000
Sports         1175000
dtype: int64

In [ ]:
#Find average sales by category.
df.mean(axis=0)

Electronics    858000.0
Groceries      437000.0
Clothing       320000.0
Furniture      283000.0
Beauty         202000.0
Sports         235000.0
dtype: float64

In [ ]:
#Find maximum sales by category.
df.max(axis=0)

Electronics    1050000
Groceries       510000
Clothing        375000
Furniture       345000
Beauty          250000
Sports          290000
dtype: int64

In [ ]:
#Find minimum sales by category.
df.min(axis=0)

Electronics    690000
Groceries      390000
Clothing       280000
Furniture      225000
Beauty         175000
Sports         205000
dtype: int64

In [ ]:
#Find total sales by city.
df.sum(axis=1)

Bangluru    2270000
Hyderbad    2295000
Chennai     2310000
Mumbai      2820000
Pune        1980000
dtype: int64

In [ ]:
#Find both sum and mean for each category.
print(df.sum(axis=0))
print(df.mean(axis=0))

Electronics    4290000
Groceries      2185000
Clothing       1600000
Furniture      1415000
Beauty         1010000
Sports         1175000
dtype: int64
Electronics    858000.0
Groceries      437000.0
Clothing       320000.0
Furniture      283000.0
Beauty         202000.0
Sports         235000.0
dtype: float64

In [ ]:
#Calculate the following for every category:
df.agg(["sum","mean","max","min"],axis=0)

      Electronics  Groceries   Clothing  Furniture     Beauty     Sports
sum     4290000.0  2185000.0  1600000.0  1415000.0  1010000.0  1175000.0
mean     858000.0   437000.0   320000.0   283000.0   202000.0   235000.0
max     1050000.0   510000.0   375000.0   345000.0   250000.0   290000.0
min      690000.0   390000.0   280000.0   225000.0   175000.0   205000.0

In [ ]:
#For each city calculate:
df.agg(["sum","mean","max","min"],axis=1)

                sum           mean        max       min
Bangluru  2270000.0  378333.333333   850000.0  190000.0
Hyderbad  2295000.0  382500.000000   780000.0  210000.0
Chennai   2310000.0  385000.000000   920000.0  185000.0
Mumbai    2820000.0  470000.000000  1050000.0  250000.0
Pune      1980000.0  330000.000000   690000.0  175000.0

In [ ]:
new.agg(["sum","mean","max","min"],axis=1)

          sum       mean        max       min
E  13590000.0  3397500.0  6888000.0  690000.0
G   6977500.0  1744375.0  3522000.0  390000.0
C   5098750.0  1274687.5  2575000.0  280000.0
F   4475000.0  1118750.0  2268000.0  225000.0
B   3231250.0   807812.5  1637000.0  175000.0
S   3761250.0   940312.5  1905000.0  205000.0

**Level 23 — pivot() / pivot_table()**

In [ ]:
new.reset_index

<bound method DataFrame.reset_index of          sum       mean        max       min
E  6888000.0  1722000.0  4290000.0  690000.0
G  3522000.0   880500.0  2185000.0  390000.0
C  2575000.0   643750.0  1600000.0  280000.0
F  2268000.0   567000.0  1415000.0  225000.0
B  1637000.0   409250.0  1010000.0  175000.0
S  1905000.0   476250.0  1175000.0  205000.0>

In [ ]:
new_df.reset_index()

      index        E       G       C       F       B       S
0  Bangluru   850000  420000  310000  275000  190000  225000
1  Hyderbad   780000  460000  295000  310000  210000  240000
2   Chennai   920000  390000  340000  260000  185000  215000
3    Mumbai  1050000  510000  375000  345000  250000  290000
4      Pune   690000  405000  280000  225000  175000  205000

In [ ]:
# Basic syntax
# df.melt(
#     id_vars=...,
#     value_vars=...,
#     var_name=...,
#     value_name=...
# )

In [ ]:
new_df_melted=new_df.reset_index().melt(
    id_vars="index",
    var_name="Product",
    value_name="Sales"
)

In [ ]:
new_df_melted

       index Product    Sales
0   Bangluru       E   850000
1   Hyderbad       E   780000
2    Chennai       E   920000
3     Mumbai       E  1050000
4       Pune       E   690000
5   Bangluru       G   420000
6   Hyderbad       G   460000
7    Chennai       G   390000
8     Mumbai       G   510000
9       Pune       G   405000
10  Bangluru       C   310000
11  Hyderbad       C   295000
12   Chennai       C   340000
13    Mumbai       C   375000
14      Pune       C   280000
15  Bangluru       F   275000
16  Hyderbad       F   310000
17   Chennai       F   260000
18    Mumbai       F   345000
19      Pune       F   225000
20  Bangluru       B   190000
21  Hyderbad       B   210000
22   Chennai       B   185000
23    Mumbai       B   250000
24      Pune       B   175000
25  Bangluru       S   225000
26  Hyderbad       S   240000
27   Chennai       S   215000
28    Mumbai       S   290000
29      Pune       S   205000

In [ ]:
df

          Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bangluru       850000     420000    310000     275000  190000  225000
Hyderbad       780000     460000    295000     310000  210000  240000
Chennai        920000     390000    340000     260000  185000  215000
Mumbai        1050000     510000    375000     345000  250000  290000
Pune           690000     405000    280000     225000  175000  205000

In [ ]:
#Sort the melted DataFrame by Sales descending.
new_df_melted.sort_index(ascending=False)

       index Product    Sales
29      Pune       S   205000
28    Mumbai       S   290000
27   Chennai       S   215000
26  Hyderbad       S   240000
25  Bangluru       S   225000
24      Pune       B   175000
23    Mumbai       B   250000
22   Chennai       B   185000
21  Hyderbad       B   210000
20  Bangluru       B   190000
19      Pune       F   225000
18    Mumbai       F   345000
17   Chennai       F   260000
16  Hyderbad       F   310000
15  Bangluru       F   275000
14      Pune       C   280000
13    Mumbai       C   375000
12   Chennai       C   340000
11  Hyderbad       C   295000
10  Bangluru       C   310000
9       Pune       G   405000
8     Mumbai       G   510000
7    Chennai       G   390000
6   Hyderbad       G   460000
5   Bangluru       G   420000
4       Pune       E   690000
3     Mumbai       E  1050000
2    Chennai       E   920000
1   Hyderbad       E   780000
0   Bangluru       E   850000

In [ ]:
new_df_melted

       index Product    Sales
0   Bangluru       E   850000
1   Hyderbad       E   780000
2    Chennai       E   920000
3     Mumbai       E  1050000
4       Pune       E   690000
5   Bangluru       G   420000
6   Hyderbad       G   460000
7    Chennai       G   390000
8     Mumbai       G   510000
9       Pune       G   405000
10  Bangluru       C   310000
11  Hyderbad       C   295000
12   Chennai       C   340000
13    Mumbai       C   375000
14      Pune       C   280000
15  Bangluru       F   275000
16  Hyderbad       F   310000
17   Chennai       F   260000
18    Mumbai       F   345000
19      Pune       F   225000
20  Bangluru       B   190000
21  Hyderbad       B   210000
22   Chennai       B   185000
23    Mumbai       B   250000
24      Pune       B   175000
25  Bangluru       S   225000
26  Hyderbad       S   240000
27   Chennai       S   215000
28    Mumbai       S   290000
29      Pune       S   205000

In [ ]:
#Find the top 5 city-category combinations.
new_df_melted.head(5)

      index Product    Sales
0  Bangluru       E   850000
1  Hyderbad       E   780000
2   Chennai       E   920000
3    Mumbai       E  1050000
4      Pune       E   690000

**Level 25 — rank()**

In [ ]:
#Rank cities based on Total Sales.
new_df.rank().sum

<bound method DataFrame.sum of             E    G    C    F    B    S
Bangluru  3.0  3.0  3.0  3.0  3.0  3.0
Hyderbad  2.0  4.0  2.0  4.0  4.0  4.0
Chennai   4.0  1.0  4.0  2.0  2.0  2.0
Mumbai    5.0  5.0  5.0  5.0  5.0  5.0
Pune      1.0  2.0  1.0  1.0  1.0  1.0>

In [ ]:
new_df.sum(axis=1).rank(method="dense")

Bangluru    2.0
Hyderbad    3.0
Chennai     4.0
Mumbai      5.0
Pune        1.0
dtype: float64

In [ ]:
new_df.rank(ascending=False,method="dense")

            E    G    C    F    B    S
Bangluru  3.0  3.0  3.0  3.0  3.0  3.0
Hyderbad  4.0  2.0  4.0  2.0  2.0  2.0
Chennai   2.0  5.0  2.0  4.0  4.0  4.0
Mumbai    1.0  1.0  1.0  1.0  1.0  1.0
Pune      5.0  4.0  5.0  5.0  5.0  5.0

In [ ]:
new_df

                E       G       C       F       B       S
Bangluru   850000  420000  310000  275000  190000  225000
Hyderbad   780000  460000  295000  310000  210000  240000
Chennai    920000  390000  340000  260000  185000  215000
Mumbai    1050000  510000  375000  345000  250000  290000
Pune       690000  405000  280000  225000  175000  205000

In [ ]:
#Rank cities based on Electronics sales.
new_df["E"].rank(ascending=False,method="dense")

Bangluru    3.0
Hyderbad    4.0
Chennai     2.0
Mumbai      1.0
Pune        5.0
Name: E, dtype: float64

In [ ]:
#Rank categories based on their total sales.
new_df.sum(axis=0).rank(ascending=True,method="dense")

E    6.0
G    5.0
C    4.0
F    3.0
B    1.0
S    2.0
dtype: float64

In [ ]:
new_df.rank(ascending=False)

            E    G    C    F    B    S
Bangluru  3.0  3.0  3.0  3.0  3.0  3.0
Hyderbad  4.0  2.0  4.0  2.0  2.0  2.0
Chennai   2.0  5.0  2.0  4.0  4.0  4.0
Mumbai    1.0  1.0  1.0  1.0  1.0  1.0
Pune      5.0  4.0  5.0  5.0  5.0  5.0

In [ ]:
#Create a Sales_Rank column.
new_df.sum().rank(ascending=False)

E    1.0
G    2.0
C    3.0
F    4.0
B    6.0
S    5.0
dtype: float64

In [ ]:
new_df["Total_sales"]=new_df.sum(axis=1)
new_df

                E       G       C       F       B       S  Total_sales
Bangluru   850000  420000  310000  275000  190000  225000    2270000.0
Hyderbad   780000  460000  295000  310000  210000  240000    2295000.0
Chennai    920000  390000  340000  260000  185000  215000    2310000.0
Mumbai    1050000  510000  375000  345000  250000  290000    2820000.0
Pune       690000  405000  280000  225000  175000  205000    1980000.0

**Level 26 — cut() / Categorization**

In [ ]:
#Divide Total Sales into three categories:
df["Sales_Category"]=pd.cut(
    new_df["Total_sales"],
    bins=[0,2000000,2500000,3000000],
    labels=["Low","Medium","High"]
)

df["Sales_Category"]

Bangluru    Medium
Hyderbad    Medium
Chennai     Medium
Mumbai        High
Pune           Low
Name: Sales_Category, dtype: category
Categories (3, str): ['Low' < 'Medium' < 'High']

In [ ]:
#Count how many cities fall into each category.
df["Sales_Category"].value_counts()

Sales_Category
Medium    3
Low       1
High      1
Name: count, dtype: int64

**Level 27 — where() / mask()**

In [ ]:
#Series.where(condition, value_if_condition_is_false)

In [151]:
#Replace Electronics sales below 800000 with 0.
new_df["E"].where(new_df["E"]>=800000,0)

Bangluru     850000
Hyderbad          0
Chennai      920000
Mumbai      1050000
Pune              0
Name: E, dtype: int64

In [155]:
#Replace Beauty sales below 200000 with NaN.
new_df["B"].mask(new_df["B"]<=200000,None)

Bangluru         NaN
Hyderbad    210000.0
Chennai          NaN
Mumbai      250000.0
Pune             NaN
Name: B, dtype: float64

In [157]:
#Replace all sales values below 200000 with "Low".
cols=["E", "G", "C", "F", "B", "S"]

new_df[cols].mask(new_df[cols]<=200000,"Low")

                E       G       C       F       B       S
Bangluru   850000  420000  310000  275000     Low  225000
Hyderbad   780000  460000  295000  310000  210000  240000
Chennai    920000  390000  340000  260000     Low  215000
Mumbai    1050000  510000  375000  345000  250000  290000
Pune       690000  405000  280000  225000     Low  205000

In [158]:
new_df

                E       G       C       F       B       S
Bangluru   850000  420000  310000  275000  190000  225000
Hyderbad   780000  460000  295000  310000  210000  240000
Chennai    920000  390000  340000  260000  185000  215000
Mumbai    1050000  510000  375000  345000  250000  290000
Pune       690000  405000  280000  225000  175000  205000

In [198]:
#Level 28 — Combining DataFrames
target_data = pd.DataFrame({
    "City": ["Bangluru", "Hyderbad", "Chennai", "Mumbai", "Pune"],
    "Target": [2200000, 2250000, 2150000, 2800000, 1900000]
})

combina=new_df.join(target_data)
combina

                E       G       C       F       B       S City  Target
Bangluru   850000  420000  310000  275000  190000  225000  NaN     NaN
Hyderbad   780000  460000  295000  310000  210000  240000  NaN     NaN
Chennai    920000  390000  340000  260000  185000  215000  NaN     NaN
Mumbai    1050000  510000  375000  345000  250000  290000  NaN     NaN
Pune       690000  405000  280000  225000  175000  205000  NaN     NaN

In [ ]:
target_data = target_data.set_index("City")

In [191]:

print(target_data)
combine=new_df.join(target_data)
combine

           Target
City
Bangluru  2200000
Hyderbad  2250000
Chennai   2150000
Mumbai    2800000
Pune      1900000

                E       G       C       F       B       S   Target
Bangluru   850000  420000  310000  275000  190000  225000  2200000
Hyderbad   780000  460000  295000  310000  210000  240000  2250000
Chennai    920000  390000  340000  260000  185000  215000  2150000
Mumbai    1050000  510000  375000  345000  250000  290000  2800000
Pune       690000  405000  280000  225000  175000  205000  1900000

In [192]:
new_df

                E       G       C       F       B       S
Bangluru   850000  420000  310000  275000  190000  225000
Hyderbad   780000  460000  295000  310000  210000  240000
Chennai    920000  390000  340000  260000  185000  215000
Mumbai    1050000  510000  375000  345000  250000  290000
Pune       690000  405000  280000  225000  175000  205000

In [203]:
new_df=new_df.reset_index()
new_df

   level_0     index        E       G       C       F       B       S
0        0  Bangluru   850000  420000  310000  275000  190000  225000
1        1  Hyderbad   780000  460000  295000  310000  210000  240000
2        2   Chennai   920000  390000  340000  260000  185000  215000
3        3    Mumbai  1050000  510000  375000  345000  250000  290000
4        4      Pune   690000  405000  280000  225000  175000  205000

In [206]:
new_df=new_df.rename(columns={"index":"City"})
new_df

   level_0      City        E       G       C       F       B       S
0        0  Bangluru   850000  420000  310000  275000  190000  225000
1        1  Hyderbad   780000  460000  295000  310000  210000  240000
2        2   Chennai   920000  390000  340000  260000  185000  215000
3        3    Mumbai  1050000  510000  375000  345000  250000  290000
4        4      Pune   690000  405000  280000  225000  175000  205000

In [207]:
#Use merge() to add Target to the sales DataFrame.
pd.merge(new_df,target_data,on="City")

   level_0      City        E       G       C       F       B       S   Target
0        0  Bangluru   850000  420000  310000  275000  190000  225000  2200000
1        1  Hyderbad   780000  460000  295000  310000  210000  240000  2250000
2        2   Chennai   920000  390000  340000  260000  185000  215000  2150000
3        3    Mumbai  1050000  510000  375000  345000  250000  290000  2800000
4        4      Pune   690000  405000  280000  225000  175000  205000  1900000

In [283]:



# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

import pandas as pd
stores = pd.DataFrame([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])


# Product categories
categories = pd.DataFrame([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])


sales_data = pd.DataFrame.from_dict({
    "Bengaluru":{"Electronics":850000, "Groceries":420000, "Clothing":310000, "Furniture":275000, "Beauty":190000, "Spots":225000},
    "Hyderbad":{"Electronics":780000, "Groceries":460000, "Clothing":295000,"Furniture": 310000, "Beauty": 210000,"Spots": 240000},
    "Chennai":{"Electronics":920000, "Groceries":390000, "Clothing":340000, "Furniture":260000,  "Beauty":185000,"Spots": 215000},
    "Mumbai":{"Electronics":1050000, "Groceries":510000, "Clothing":375000, "Furniture":345000, "Beauty": 250000,"Spots": 290000},
    "Pune":{"Electronics":690000, "Groceries":405000, "Clothing":280000,"Furniture": 225000,  "Beauty":175000, "Spots":205000}
},orient="index")


# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = pd.DataFrame.from_dict({
    "Bengaluru":{"Electronics":640000,"Groceries": 315000, "Clothing":220000, "Furniture":205000,"Beauty" :125000,"Spots": 160000},
    "Hyderbad":{"Electronics":590000, "Groceries":350000, "Clothing":210000, "Furniture":225000,"Beauty": 140000,"Spots" :170000},
    "Chennai":{"Electronics":700000, "Groceries":295000,"Clothing": 245000,"Furniture": 195000,"Beauty": 120000,"Spots": 155000},
    "Mumbai":{"Electronics":790000, "Groceries":390000, "Clothing":265000,"Furniture": 250000,"Beauty": 165000,"Spots": 205000},
    "Pune":{"Electronics":530000, "Groceries":310000, "Clothing":205000,"Furniture": 170000,"Beauty": 115000,"Spots" :145000}
},orient="index")

**Level 1 — Creating & Inspecting DataFrames**

In [44]:
#Print the stores DataFrame.
stores

           0
0  Bengaluru
1  Hyderabad
2    Chennai
3     Mumbai
4       Pune

In [45]:
#Print the categories DataFrame.
categories

             0
0  Electronics
1    Groceries
2     Clothing
3    Furniture
4       Beauty
5       Sports

In [46]:
#Print the sales_data DataFrame.
sales_data

           Electronics  Groceries  Clothing  Furniture  Beauty   Spots
Bengaluru       850000     420000    310000     275000  190000  225000
Hyderbad        780000     460000    295000     310000  210000  240000
Chennai         920000     390000    340000     260000  185000  215000
Mumbai         1050000     510000    375000     345000  250000  290000
Pune            690000     405000    280000     225000  175000  205000

In [47]:
#Print the cost_data DataFrame.
cost_data

           Electronics  Groceries  Clothing  Furniture  Beauty   Spots
Bengaluru       640000     315000    220000     205000  125000  160000
Hyderbad        590000     350000    210000     225000  140000  170000
Chennai         700000     295000    245000     195000  120000  155000
Mumbai          790000     390000    265000     250000  165000  205000
Pune            530000     310000    205000     170000  115000  145000

In [48]:
#Find the number of rows and columns in sales_data using .shape.
sales_data.shape

(5, 6)

In [13]:
#Find the number of rows and columns in cost_data.
cost_data.shape

(5, 6)

In [49]:
#Display the first 3 rows of sales_data using .head().
sales_data.head(3)

           Electronics  Groceries  Clothing  Furniture  Beauty   Spots
Bengaluru       850000     420000    310000     275000  190000  225000
Hyderbad        780000     460000    295000     310000  210000  240000
Chennai         920000     390000    340000     260000  185000  215000

In [50]:
#Display the last 2 rows of sales_data using .tail().
sales_data.tail(2)

        Electronics  Groceries  Clothing  Furniture  Beauty   Spots
Mumbai      1050000     510000    375000     345000  250000  290000
Pune         690000     405000    280000     225000  175000  205000

In [51]:
#Check the data types of sales_data using .dtypes.
sales_data.dtypes

Electronics    int64
Groceries      int64
Clothing       int64
Furniture      int64
Beauty         int64
Spots          int64
dtype: object

In [52]:
sales_data.describe()

,Electronics,Groceries,Clothing,Furniture,Beauty,Spots
count,5.000000e+00,5.000000,5.00000,5.000000,5.000000,5.00000
mean,8.580000e+05,437000.000000,320000.00000,283000.000000,202000.000000,235000.00000
std,1.370036e+05,48425.200051,37914.37722,46178.999556,29706.901555,33354.16016
min,6.900000e+05,390000.000000,280000.00000,225000.000000,175000.000000,205000.00000
25%,7.800000e+05,405000.000000,295000.00000,260000.000000,185000.000000,215000.00000
50%,8.500000e+05,420000.000000,310000.00000,275000.000000,190000.000000,225000.00000
75%,9.200000e+05,460000.000000,340000.00000,310000.000000,210000.000000,240000.00000
max,1.050000e+06,510000.000000,375000.00000,345000.000000,250000.000000,290000.00000

**Level 2 — Basic Selection**

In [53]:
#Select the first column of sales_data.
sales_data.iloc[:,0]

Bengaluru     850000
Hyderbad      780000
Chennai       920000
Mumbai       1050000
Pune          690000
Name: Electronics, dtype: int64

In [54]:
#Select the first row of sales_data using .iloc.
sales_data.iloc[0]

Electronics    850000
Groceries      420000
Clothing       310000
Furniture      275000
Beauty         190000
Spots          225000
Name: Bengaluru, dtype: int64

In [55]:
#Select the third row of sales_data.
sales_data.iloc[3]

Electronics    1050000
Groceries       510000
Clothing        375000
Furniture       345000
Beauty          250000
Spots           290000
Name: Mumbai, dtype: int64

In [56]:
#Select the Electronics and Groceries columns from sales_data.
sales_data.iloc[:,0:2]

           Electronics  Groceries
Bengaluru       850000     420000
Hyderbad        780000     460000
Chennai         920000     390000
Mumbai         1050000     510000
Pune            690000     405000

In [57]:
#Select the sales of Mumbai.
print(stores.iloc[3])
print(sales_data.iloc[3])

0    Mumbai
Name: 3, dtype: str
Electronics    1050000
Groceries       510000
Clothing        375000
Furniture       345000
Beauty          250000
Spots           290000
Name: Mumbai, dtype: int64

In [63]:
#Select the sales of Bengaluru and Chennai.
sale=sales_data.loc[["Bengaluru","Chennai"]]
sale

           Electronics  Groceries  Clothing  Furniture  Beauty   Spots
Bengaluru       850000     420000    310000     275000  190000  225000
Chennai         920000     390000    340000     260000  185000  215000

In [29]:
stores

           0
0  Bengaluru
1  Hyderabad
2    Chennai
3     Mumbai
4       Pune

In [67]:
#Select the sales of Clothing, Furniture, and Beauty for all stores.
sales_data[["Clothing","Furniture","Beauty"]]

           Clothing  Furniture  Beauty
Bengaluru    310000     275000  190000
Hyderbad     295000     310000  210000
Chennai      340000     260000  185000
Mumbai       375000     345000  250000
Pune         280000     225000  175000

In [71]:
#Select the sales of Electronics for Mumbai.
sales_data.loc["Mumbai","Electronics"]

np.int64(1050000)

**Level 3 — Aggregation Functions**

In [72]:
#Find the total sales for each product category.
sales_data.sum(axis=0)

Electronics    4290000
Groceries      2185000
Clothing       1600000
Furniture      1415000
Beauty         1010000
Spots          1175000
dtype: int64

In [73]:
#Find the total sales for each store.
sales_data.sum(axis=1)

Bengaluru    2270000
Hyderbad     2295000
Chennai      2310000
Mumbai       2820000
Pune         1980000
dtype: int64

In [75]:
#Find the average sales for each product category.
sales_data.mean(axis=0)

Electronics    858000.0
Groceries      437000.0
Clothing       320000.0
Furniture      283000.0
Beauty         202000.0
Spots          235000.0
dtype: float64

In [76]:
#Find the maximum sales in each category.
sales_data.max()

Electronics    1050000
Groceries       510000
Clothing        375000
Furniture       345000
Beauty          250000
Spots           290000
dtype: int64

In [77]:
#Find the minimum sales in each category.
sales_data.min()

Electronics    690000
Groceries      390000
Clothing       280000
Furniture      225000
Beauty         175000
Spots          205000
dtype: int64

In [78]:
#Find the total cost for each product category.
cost_data.sum()

Electronics    3250000
Groceries      1660000
Clothing       1145000
Furniture      1045000
Beauty          665000
Spots           835000
dtype: int64

In [79]:
#Find the total cost for each store.
cost_data.sum(axis=1)

Bengaluru    1665000
Hyderbad     1685000
Chennai      1710000
Mumbai       2065000
Pune         1475000
dtype: int64

In [80]:
#Find the average cost for each category.
cost_data.mean()

Electronics    650000.0
Groceries      332000.0
Clothing       229000.0
Furniture      209000.0
Beauty         133000.0
Spots          167000.0
dtype: float64

**Level 4 — Basic DataFrame Operations**

In [81]:
#Add the store names as the index of sales_data.
sales_data

           Electronics  Groceries  Clothing  Furniture  Beauty   Spots
Bengaluru       850000     420000    310000     275000  190000  225000
Hyderbad        780000     460000    295000     310000  210000  240000
Chennai         920000     390000    340000     260000  185000  215000
Mumbai         1050000     510000    375000     345000  250000  290000
Pune            690000     405000    280000     225000  175000  205000

In [241]:
stores = pd.DataFrame([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

In [285]:
sale_data =pd.DataFrame([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

In [287]:
sale_data.index=stores
sale_data

                    0       1       2       3       4       5
(Bengaluru,)   850000  420000  310000  275000  190000  225000
(Hyderabad,)   780000  460000  295000  310000  210000  240000
(Chennai,)     920000  390000  340000  260000  185000  215000
(Mumbai,)     1050000  510000  375000  345000  250000  290000
(Pune,)        690000  405000  280000  225000  175000  205000

In [288]:
#Add the category names as the columns of sales_data.
sale_data.columns=categories
sale_data

,"(Electronics,)","(Groceries,)","(Clothing,)","(Furniture,)","(Beauty,)","(Sports,)"
"(Bengaluru,)",850000,420000,310000,275000,190000,225000
"(Hyderabad,)",780000,460000,295000,310000,210000,240000
"(Chennai,)",920000,390000,340000,260000,185000,215000
"(Mumbai,)",1050000,510000,375000,345000,250000,290000
"(Pune,)",690000,405000,280000,225000,175000,205000

In [284]:
#Do the same for cost_data.
# NumPy Retail Analytics Assignment
cos_data=pd.DataFrame([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

In [286]:
cos_data.index=stores
cos_data.columns=categories

In [247]:
cos_data

,"(Electronics,)","(Groceries,)","(Clothing,)","(Furniture,)","(Beauty,)","(Sports,)"
"(Bengaluru,)",640000,315000,220000,205000,125000,160000
"(Hyderabad,)",590000,350000,210000,225000,140000,170000
"(Chennai,)",700000,295000,245000,195000,120000,155000
"(Mumbai,)",790000,390000,265000,250000,165000,205000
"(Pune,)",530000,310000,205000,170000,115000,145000

In [105]:
#Find the total sales of Bengaluru across all categories.
sales_data.loc["Bengaluru"].sum()

np.int64(2270000)

In [106]:
#Find the total sales of Mumbai across all categories.
sales_data.loc["Mumbai"].sum()

np.int64(2820000)

In [ ]:
#Which city has the highest total sales?
total=df.sum(axis=1)
index=total.idxmax()
max_total=total.max()
# print(total)
print(index)
# print(total.loc[index])
print(max_total)

In [113]:
#Find which store has the highest total sales.
total=sales_data.sum(axis=1)
city=total.idxmax()
max_total=total.max()
print(city,"-",max_total)

Mumbai - 2820000

In [117]:
#Find which category has the highest total sales.
total=sales_data.sum(axis=0)
cat=total.idxmax()
max_cat=total.max()
print(cat,"-",max_cat)

Electronics - 4290000

In [118]:
#Find which store has the lowest total sales.
total=sales_data.sum(axis=1)
city=total.idxmin()
min_val=total.min()
print(city,min_val)

Pune 1980000

**Level 5 — Sales vs Cost**

In [120]:
profit=sales_data-cost_data
profit

           Electronics  Groceries  Clothing  Furniture  Beauty  Spots
Bengaluru       210000     105000     90000      70000   65000  65000
Hyderbad        190000     110000     85000      85000   70000  70000
Chennai         220000      95000     95000      65000   65000  60000
Mumbai          260000     120000    110000      95000   85000  85000
Pune            160000      95000     75000      55000   60000  60000

In [248]:
print(sales_data,cost_data)

           Electronics  Groceries  Clothing  Furniture  Beauty   Spots
Bengaluru       850000     420000    310000     275000  190000  225000
Hyderbad        780000     460000    295000     310000  210000  240000
Chennai         920000     390000    340000     260000  185000  215000
Mumbai         1050000     510000    375000     345000  250000  290000
Pune            690000     405000    280000     225000  175000  205000            Electronics  Groceries  Clothing  Furniture  Beauty   Spots
Bengaluru       640000     315000    220000     205000  125000  160000
Hyderbad        590000     350000    210000     225000  140000  170000
Chennai         700000     295000    245000     195000  120000  155000
Mumbai          790000     390000    265000     250000  165000  205000
Pune            530000     310000    205000     170000  115000  145000

In [122]:
#Find the total profit for each store.
profit.sum(axis=1)

Bengaluru    605000
Hyderbad     610000
Chennai      600000
Mumbai       755000
Pune         505000
dtype: int64

In [123]:
#Find the total profit for each category.
profit.sum(axis=0)

Electronics    1040000
Groceries       525000
Clothing        455000
Furniture       370000
Beauty          345000
Spots           340000
dtype: int64

In [126]:
#Find the store with the highest total profit.
total=profit.sum(axis=1)
city_pro=total.idxmax()
val=total.max()
print(city,val)

Pune 755000

In [128]:
#Find the category with the highest total profit.
total=profit.sum(axis=0)
city_po=total.idxmax()
val=total.max()
print(city_po,val)

Electronics 1040000

In [129]:
#Find the profit for Mumbai → Electronics.
profit.loc["Mumbai"]["Electronics"]

np.int64(260000)

**Challenge Questions**

In [132]:
#Which store has the highest Electronics sales?
ci=sales_data["Electronics"].idxmax()
sa=sales_data["Electronics"].max()
print(ci,sa)

Mumbai 1050000

In [139]:
#Which category has the highest sales in Mumbai?
ci=sales_data.loc["Mumbai"].idxmax()
va=sales_data.loc["Mumbai"].max()
print(ci,va)

Electronics 1050000

In [143]:
#What is the total sales across all stores and categories?
sales_data.sum().sum()

np.int64(11675000)

In [144]:
#What is the total cost across all stores and categories?
cost_data.sum().sum()

np.int64(8600000)

In [145]:
#What is the overall profit?
profit.sum().sum()

np.int64(3075000)

In [148]:
#Calculate the profit percentage:
profit_margin=profit/sales_data*100
round(profit_margin,2)

           Electronics  Groceries  Clothing  Furniture  Beauty  Spots
Bengaluru        24.71      25.00     29.03      25.45   34.21  28.89
Hyderbad         24.36      23.91     28.81      27.42   33.33  29.17
Chennai          23.91      24.36     27.94      25.00   35.14  27.91
Mumbai           24.76      23.53     29.33      27.54   34.00  29.31
Pune             23.19      23.46     26.79      24.44   34.29  29.27

In [150]:
#Find the category with the highest profit percentage.
ci=profit_margin.idxmax(axis=0)
va=profit_margin.max(axis=0)
print(ci,va)

Electronics       Mumbai
Groceries      Bengaluru
Clothing          Mumbai
Furniture         Mumbai
Beauty           Chennai
Spots             Mumbai
dtype: str Electronics    24.761905
Groceries      25.000000
Clothing       29.333333
Furniture      27.536232
Beauty         35.135135
Spots          29.310345
dtype: float64

In [155]:
#Find the store with the highest profit percentage.
total=profit_margin.sum(axis=1)
ci=total.idxmax()
va=total.max()
print(total,ci,va)

Bengaluru    167.292101
Hyderbad     167.004932
Chennai      164.255306
Mumbai       168.471227
Pune         161.429362
dtype: float64 Mumbai 168.47122657158812

**Part 1 — Filtering**

In [157]:
#Find all stores where Electronics sales are greater than ₹800,000.
sales_data[sales_data["Electronics"]>800000]

           Electronics  Groceries  Clothing  Furniture  Beauty   Spots
Bengaluru       850000     420000    310000     275000  190000  225000
Chennai         920000     390000    340000     260000  185000  215000
Mumbai         1050000     510000    375000     345000  250000  290000

In [158]:
#Find all stores where Groceries sales are less than ₹450,000.
sales_data[sales_data["Groceries"]<450000]

           Electronics  Groceries  Clothing  Furniture  Beauty   Spots
Bengaluru       850000     420000    310000     275000  190000  225000
Chennai         920000     390000    340000     260000  185000  215000
Pune            690000     405000    280000     225000  175000  205000

In [161]:
#Find stores where Electronics sales > ₹800,000 AND Clothing sales > ₹300,000.
sales_data[(sales_data["Electronics"]>800000) & (sales_data["Clothing"]>300000)]

           Electronics  Groceries  Clothing  Furniture  Beauty   Spots
Bengaluru       850000     420000    310000     275000  190000  225000
Chennai         920000     390000    340000     260000  185000  215000
Mumbai         1050000     510000    375000     345000  250000  290000

In [163]:
#Find stores where Furniture sales are greater than ₹250,000 OR Beauty sales are greater than ₹200,000.
sales_data[(sales_data["Furniture"]>250000) | (sales_data["Beauty"]>200000)]

           Electronics  Groceries  Clothing  Furniture  Beauty   Spots
Bengaluru       850000     420000    310000     275000  190000  225000
Hyderbad        780000     460000    295000     310000  210000  240000
Chennai         920000     390000    340000     260000  185000  215000
Mumbai         1050000     510000    375000     345000  250000  290000

In [166]:
#Find all rows where total sales across all categories are greater than ₹2,000,000.
sales_data[sales_data.sum(axis=1)>2000000]

           Electronics  Groceries  Clothing  Furniture  Beauty   Spots
Bengaluru       850000     420000    310000     275000  190000  225000
Hyderbad        780000     460000    295000     310000  210000  240000
Chennai         920000     390000    340000     260000  185000  215000
Mumbai         1050000     510000    375000     345000  250000  290000

In [199]:
sale_data.index=stores
sale_data

                    0       1       2       3       4       5
(Bengaluru,)   850000  420000  310000  275000  190000  225000
(Hyderabad,)   780000  460000  295000  310000  210000  240000
(Chennai,)     920000  390000  340000  260000  185000  215000
(Mumbai,)     1050000  510000  375000  345000  250000  290000
(Pune,)        690000  405000  280000  225000  175000  205000

In [201]:
sale_data.columns=categories

In [203]:
sale_data

,"(Electronics,)","(Groceries,)","(Clothing,)","(Furniture,)","(Beauty,)","(Sports,)"
"(Bengaluru,)",850000,420000,310000,275000,190000,225000
"(Hyderabad,)",780000,460000,295000,310000,210000,240000
"(Chennai,)",920000,390000,340000,260000,185000,215000
"(Mumbai,)",1050000,510000,375000,345000,250000,290000
"(Pune,)",690000,405000,280000,225000,175000,205000

In [207]:
#Create a column called Total_Sales containing the total sales of each store.
sale_data["Total_sales"]=sale_data.sum(axis=1)

# sale_data.drop(columns="Total_Sales")
sale_data

,"(Electronics,)","(Groceries,)","(Clothing,)","(Furniture,)","(Beauty,)","(Sports,)",Total_sales
"(Bengaluru,)",850000,420000,310000,275000,190000,225000,6810000
"(Hyderabad,)",780000,460000,295000,310000,210000,240000,6885000
"(Chennai,)",920000,390000,340000,260000,185000,215000,6930000
"(Mumbai,)",1050000,510000,375000,345000,250000,290000,8460000
"(Pune,)",690000,405000,280000,225000,175000,205000,5940000

In [206]:
sale_data

,"(Electronics,)","(Groceries,)","(Clothing,)","(Furniture,)","(Beauty,)","(Sports,)",Total_sales
"(Bengaluru,)",850000,420000,310000,275000,190000,225000,4540000
"(Hyderabad,)",780000,460000,295000,310000,210000,240000,4590000
"(Chennai,)",920000,390000,340000,260000,185000,215000,4620000
"(Mumbai,)",1050000,510000,375000,345000,250000,290000,5640000
"(Pune,)",690000,405000,280000,225000,175000,205000,3960000

In [209]:
#Create a Total_Cost column using cost_data.
cos_data["Total_cost"]=cos_data.sum(axis=1)
cos_data

        0       1       2       3       4       5  Total_cost
0  640000  315000  220000  205000  125000  160000     3330000
1  590000  350000  210000  225000  140000  170000     3370000
2  700000  295000  245000  195000  120000  155000     3420000
3  790000  390000  265000  250000  165000  205000     4130000
4  530000  310000  205000  170000  115000  145000     2950000

In [ ]:
#Create a Total_Profit column:
profit["Total_pofit"]=profit.sum(axis=1)
profit

,Electronics,Groceries,Clothing,Furniture,Beauty,Spots,Total_pofit
Bengaluru,210000,105000,90000,70000,65000,65000,3025000
Hyderbad,190000,110000,85000,85000,70000,70000,3050000
Chennai,220000,95000,95000,65000,65000,60000,3000000
Mumbai,260000,120000,110000,95000,85000,85000,3775000
Pune,160000,95000,75000,55000,60000,60000,2525000

In [221]:
profit.drop(columns=["Total_pofit"])

           Electronics  Groceries  Clothing  Furniture  Beauty  Spots
Bengaluru       210000     105000     90000      70000   65000  65000
Hyderbad        190000     110000     85000      85000   70000  70000
Chennai         220000      95000     95000      65000   65000  60000
Mumbai          260000     120000    110000      95000   85000  85000
Pune            160000      95000     75000      55000   60000  60000

In [250]:
sales_data

           Electronics  Groceries  Clothing  Furniture  Beauty   Spots
Bengaluru       850000     420000    310000     275000  190000  225000
Hyderbad        780000     460000    295000     310000  210000  240000
Chennai         920000     390000    340000     260000  185000  215000
Mumbai         1050000     510000    375000     345000  250000  290000
Pune            690000     405000    280000     225000  175000  205000

In [ ]:
total_sale=sale_data.sum(axis=1)
cos_data=cos_data.sum(axis=1)

In [254]:
total_profit=total_sale-cos_data
print(total_profit)

(Bengaluru,)    605000
(Hyderabad,)    610000
(Chennai,)      600000
(Mumbai,)       755000
(Pune,)         505000
dtype: int64

In [256]:
profit_per=total_profit/total_sale*100
profit_per

(Bengaluru,)    26.651982
(Hyderabad,)    26.579521
(Chennai,)      25.974026
(Mumbai,)       26.773050
(Pune,)         25.505051
dtype: float64

In [258]:
print(round(profit_per))
print(round(profit_per,2))

(Bengaluru,)    27.0
(Hyderabad,)    27.0
(Chennai,)      26.0
(Mumbai,)       27.0
(Pune,)         26.0
dtype: float64
(Bengaluru,)    26.65
(Hyderabad,)    26.58
(Chennai,)      25.97
(Mumbai,)       26.77
(Pune,)         25.51
dtype: float64

**Part 3 — Sorting**

In [268]:
#Sort stores by Total_Sales from highest to lowest.
total_sale.sort_values(ascending=False)

(Mumbai,)       2820000
(Chennai,)      2310000
(Hyderabad,)    2295000
(Bengaluru,)    2270000
(Pune,)         1980000
dtype: int64

In [269]:
#Sort stores by Total_Profit from lowest to highest.
profit.sum(axis=1).sort_values()

Pune         3030000
Chennai      3600000
Bengaluru    3630000
Hyderbad     3660000
Mumbai       4530000
dtype: int64

In [271]:
#Find the top 3 stores based on Total Sales.
sale_data.sum(axis=1).head(3)

(Bengaluru,)    2270000
(Hyderabad,)    2295000
(Chennai,)      2310000
dtype: int64

In [272]:
#Find the bottom 2 stores based on Total Profit.
profit.sum(axis=1).tail(2)

Mumbai    4530000
Pune      3030000
dtype: int64

In [275]:
#Sort the DataFrame first by Total_Sales descending and then by Profit_Percentage descending.
sale_data.sum(axis=1).sort_values(ascending=False)

(Mumbai,)       2820000
(Chennai,)      2310000
(Hyderabad,)    2295000
(Bengaluru,)    2270000
(Pune,)         1980000
dtype: int64

**Part 4 — idxmax() / idxmin()**

In [294]:
#Find the store with the highest Electronics sales.
high=sales_data["Electronics"].idxmax()
city=sales_data["Electronics"].max()
print(high,city)

Mumbai 1050000

In [297]:
#Find the store with the lowest Electronics sales.
low=sales_data["Electronics"].idxmin()
ci=sales_data["Electronics"].min()
print(low,ci)

Pune 690000

In [299]:
#Find the category with the highest total sales.
print(sale_data.sum(axis=0).max())
print(sales_data.sum(axis=0).idxmax())

4290000
Electronics

In [300]:
#Find the category with the lowest total sales.
print(sale_data.sum(axis=0).min())
print(sales_data.sum(axis=0).idxmin())

1010000
Beauty

In [302]:
#Find the store with the highest Total Profit.
profit=sales_data-cost_data
profit.idxmax(axis=1)

Bengaluru    Electronics
Hyderbad     Electronics
Chennai      Electronics
Mumbai       Electronics
Pune         Electronics
dtype: str

In [314]:
#Find the store with the highest Profit Percentage.
# pro=profit_margin.max()
# ci=profit_margin.idxmax()
# print(pro,ci)
to_sa=sales_data.sum(axis=1)
to_co=cost_data.sum(axis=1)
to_profit=to_sa-to_co
profit_mar=to_profit/to_sa*100
profit_mar.idxmax()
profit_mar.max()

np.float64(26.773049645390074)

**Part 5 — axis**

In [307]:
#Calculate the total sales for every store using:
sale_data.sum(axis=1)

(Bengaluru,)    2270000
(Hyderabad,)    2295000
(Chennai,)      2310000
(Mumbai,)       2820000
(Pune,)         1980000
dtype: int64

In [308]:
#Calculate the total sales for every category using:
sale_data.sum(axis=0)

(Electronics,)    4290000
(Groceries,)      2185000
(Clothing,)       1600000
(Furniture,)      1415000
(Beauty,)         1010000
(Sports,)         1175000
dtype: int64